version: '3'
services:
  logger-app:
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - 4000:80
  postgres:
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
volumes:
  pgdata: